state_sa_name = "srakstfstate3"
container_name = "akscs"
access_key = "cpmfxT4vUMzu+74Qx06Kf5yHrmjzazI8mAyzCXzr6aTkGo5obvp3QlHLjMQYkRXsuHbnZaYwIhYJ+AStPAw4Kw=="
prefix = "srtest"
private_dns_zone_name = "privatelink.eastus.azmk8s.io"
